import { CaseDossier, InvestigationResult, RAGSourceEvidence } from "./types";

export const MOCK_CASES: Record<string, CaseDossier> = {
  "CASE-001": {
    case_id: "CASE-001",
    title: "CASE-001: Missing Timeline",
    subtitle: "Temporal Gap in Transit Corridors",
    age: 14,
    origin: "Patna",
    timeline: "Last seen at Patna Junction on 2026-09-01 08:30 IST",
    physical_markers: "Scar on left forearm, height 150cm",
    registered_hub: "East Central Railway (ECR) Danapur / Patna Junction",
    exact_address: "House No. 42, Ward 7, Kankarbagh, Patna, Bihar 800020",
    biometric_hash: "sha256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069",
    contact_number: "+91-9876543210",
    raw_intake:
      "Subject last seen at Patna Junction on 2026-09-01. Route and transit history unverified across rail manifests.",
    similarity_score: 0.88,
    initial_entropy: 1.0,
    target_entropy: 0.35,
  },
  "CASE-002": {
    case_id: "CASE-002",
    title: "CASE-002: Hard Contradiction Override",
    subtitle: "High Biometric Match with Ground-Truth Contradiction",
    age: 16,
    origin: "Ranchi",
    timeline: "Reported missing from Ranchi Bus Stand on 2026-09-03 14:00 IST",
    physical_markers: "Mole on right cheek, black hair; verified scar on left forearm",
    registered_hub: "Birsa Munda Interstate Bus Terminal (ISBT) Bay 4",
    exact_address: "Flat 302, Green Valley Apartments, Morabadi, Ranchi, Jharkhand 834008",
    biometric_hash: "sha256:4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a",
    contact_number: "+91-9123456780",
    raw_intake:
      "Facial recognition match score 98.4% at Ranchi Bus Stand. Field report indicates subject has a prominent scar on right forearm, whereas verified case records confirm scar on left forearm. Physical marker contradiction detected: left forearm != right forearm.",
    similarity_score: 0.94,
    initial_entropy: 1.0,
    target_entropy: 0.85,
  },
  "CASE-003": {
    case_id: "CASE-003",
    title: "CASE-003: Clean Evidence",
    subtitle: "Full Documentary Corroboration & Zero Anomalies",
    age: 12,
    origin: "Varanasi",
    timeline: "Missing from Godowlia Chowk since 2026-09-05 18:45 IST",
    physical_markers: "Wearing red wristband, height 138cm",
    registered_hub: "Varanasi Smart City Grid (Godowlia Chowk CCTV Cam-14)",
    exact_address: "Plot 12, Dashashwamedh Road, Varanasi, Uttar Pradesh 221001",
    biometric_hash: "sha256:ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d",
    contact_number: "+91-9988776655",
    raw_intake:
      "Complete verified documentary case intake with corroborating municipal records, biometric confirmation, and zero anomalies.",
    similarity_score: 0.98,
    initial_entropy: 1.0,
    target_entropy: 0.0,
  },
};

export const MOCK_RESULTS: Record<string, InvestigationResult> = {
  "CASE-001": {
    case_id: "CASE-001",
    terminal_state: "INVESTIGATE",
    final_entropy: 0.35,
    entropy_history: [1.0, 0.75, 0.5, 0.35],
    policy_rule_triggered: "Policy Rule 4: Dimension Unconfirmed (Timeline pending field check)",
    similarity_score: 0.88,
    contradictions: [],
    quarantine_log: {
      blocked_fields: ["exact_address", "biometric_hash", "contact_number"],
      safe_fields: ["age", "origin", "timeline", "physical_markers"],
      zero_pii_verified: true,
    },
    uncertainty_budget: {
      identity: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.95,
        sources: ["initial_records", "aadhaar_vault_token"],
      },
      origin: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.95,
        sources: ["initial_records", "patna_police_fir_2026"],
      },
      timeline: {
        required: true,
        status: "MISSING",
        confidence: 0.45,
        sources: ["vector_rag:cctv_patna_railway"],
      },
      physical_markers: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.95,
        sources: ["initial_records", "medical_intake_pmch"],
      },
    },
    steps: [
      {
        step: 1,
        node: "manager",
        plane: "Plane 1: Intake & Security Audit",
        title: "Case Manager Agent",
        icon: "🧭",
        tool: "scan_prompt_injection() & Dynamic Uncertainty Routing",
        toolType: "Security Audit",
        reasoning:
          "3-Tier jailbreak audit completed: Tier 1 regex pass, Tier 2 structural entropy pass, Tier 3 semantic risk 0.02. Dynamic budget analysis identifies 'timeline' dimension as MISSING (confidence 0.0). Routing task to Context Investigator.",
        timestamp: "2026-09-11 13:30:14.102 IST",
        entropy: 1.0,
      },
      {
        step: 2,
        node: "context_inv",
        plane: "Plane 2: FastMCP & RAG Investigators",
        title: "Context Investigator",
        icon: "⏱️",
        tool: "FastMCP: check_case_timeline(origin='Patna', dest='Danapur', date='2026-09-01')",
        toolType: "FastMCP",
        reasoning:
          "Queried FastMCP check_case_timeline tool and ChromaDB hybrid vector store. Found candidate transit route RAIL-09 (28h estimated transit). Corroborated sighting at Patna Jn Cam-04, but connecting bus leg unconfirmed.",
        timestamp: "2026-09-11 13:30:14.340 IST",
        entropy: 0.75,
      },
      {
        step: 3,
        node: "critic",
        plane: "Plane 3: Adversarial Safety Critic",
        title: "Safety Critic Agent",
        icon: "⚖️",
        tool: "Dual-Mode LLM Gateway: audit_contradictions()",
        toolType: "Dual-Mode LLM",
        reasoning:
          "Evaluated multi-source evidence for contradictions. Zero physical marker anomalies detected. Soft ambiguity on transit transfer window (45 min gap), classified as NON-CRITICAL.",
        timestamp: "2026-09-11 13:30:14.512 IST",
        entropy: 0.5,
      },
      {
        step: 4,
        node: "policy_eval",
        plane: "The +1 Plane: Deterministic Policy Engine",
        title: "Policy Evaluator Engine",
        icon: "🛡️",
        tool: "Zero-LLM Governance Rules Engine (Rule 4 Triggered)",
        toolType: "Deterministic Policy",
        reasoning:
          "Policy Engine evaluated Rule 4: Required dimension 'timeline' is not fully confirmed (< 0.90 threshold). Automated escalation withheld. Action: Dispatch FastMCP municipal resource request to verify connecting transit CCTV.",
        timestamp: "2026-09-11 13:30:14.620 IST",
        terminal_state: "INVESTIGATE",
        entropy: 0.35,
      },
    ],
  },
  "CASE-002": {
    case_id: "CASE-002",
    terminal_state: "HOLD",
    final_entropy: 0.85,
    entropy_history: [1.0, 0.9, 0.85, 0.85],
    policy_rule_triggered: "Policy Rule 1: HARD CONTRADICTION > SIMILARITY (Immutable Override)",
    similarity_score: 0.94,
    contradictions: [
      {
        dimension: "physical_markers",
        type: "HARD",
        source_a: "Transit Sighting CCTV Field Manifest (Ranchi ISBT Bay 4)",
        source_b: "Official Medical Registry & Intake Records (Patna / Ranchi)",
        reason: "Physical marker contradiction detected: left forearm != right forearm",
      },
    ],
    quarantine_log: {
      blocked_fields: ["exact_address", "biometric_hash", "contact_number"],
      safe_fields: ["age", "origin", "timeline", "physical_markers"],
      zero_pii_verified: true,
    },
    uncertainty_budget: {
      identity: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.91,
        sources: ["vector_rag:cctv_ranchi_bus_stand", "facial_rec_model_v3"],
      },
      origin: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.87,
        sources: ["ranchi_municipal_dossier"],
      },
      timeline: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.93,
        sources: ["isbt_bay_4_manifest", "interstate_ticket_scan"],
      },
      physical_markers: {
        required: true,
        status: "CONTRADICTED",
        confidence: 0.2,
        sources: ["field_report_ranchi", "verified_medical_dossier"],
      },
    },
    steps: [
      {
        step: 1,
        node: "manager",
        plane: "Plane 1: Intake & Security Audit",
        title: "Case Manager Agent",
        icon: "🧭",
        tool: "scan_prompt_injection() & Dynamic Uncertainty Routing",
        toolType: "Security Audit",
        reasoning:
          "Intake security passed (Tier 1-3 zero threat). Raw intake notes high biometric similarity: Facial recognition match 98.4%, overall match score 94.0%. Initial uncertainty budget set to H=1.00. Routing to Evidence Investigator for physical confirmation.",
        timestamp: "2026-09-11 13:30:15.010 IST",
        entropy: 1.0,
      },
      {
        step: 2,
        node: "evidence_inv",
        plane: "Plane 2: FastMCP & RAG Investigators",
        title: "Evidence Investigator",
        icon: "🔎",
        tool: "FastMCP: search_case_metadata(case_id='CASE-002', requested_fields=['physical_markers', 'age'])",
        toolType: "FastMCP",
        reasoning:
          "FastMCP Pre-LLM Quarantine Gate intercepted query. Sanitized request: 3 sensitive fields (exact_address, biometric_hash, contact_number) strictly blocked. Allowed metadata returned: 'Scar on left forearm'. Field sighting states: 'Scar on right forearm'.",
        timestamp: "2026-09-11 13:30:15.220 IST",
        entropy: 0.9,
      },
      {
        step: 3,
        node: "critic",
        plane: "Plane 3: Adversarial Safety Critic",
        title: "Safety Critic Agent",
        icon: "⚖️",
        tool: "Dual-Mode LLM Gateway: audit_contradictions()",
        toolType: "Dual-Mode LLM",
        reasoning:
          "CRITICAL CONTRADICTION DETECTED: Ground-truth anatomy conflict. Sighting subject bears prominent scar on RIGHT forearm, verified case dossier records scar on LEFT forearm. Marked as HARD CONTRADICTION.",
        timestamp: "2026-09-11 13:30:15.480 IST",
        entropy: 0.85,
        contradictions: [
          {
            dimension: "physical_markers",
            type: "HARD",
            source_a: "Transit Sighting CCTV Field Manifest (Ranchi ISBT Bay 4)",
            source_b: "Official Medical Registry & Intake Records (Patna / Ranchi)",
            reason: "Physical marker contradiction detected: left forearm != right forearm",
          },
        ],
      },
      {
        step: 4,
        node: "policy_eval",
        plane: "The +1 Plane: Deterministic Policy Engine",
        title: "Policy Evaluator Engine",
        icon: "🛡️",
        tool: "Deterministic Governance Engine (Rule 1 Enforced)",
        toolType: "Deterministic Policy",
        reasoning:
          "POLICY RULE 1 TRIGGERED: HARD CONTRADICTION > SIMILARITY. High similarity score (94.0%) and high facial match (98.4%) categorically discarded due to physical ground-truth anatomical contradiction. System executes supervisory halt: Final State = HOLD.",
        timestamp: "2026-09-11 13:30:15.610 IST",
        terminal_state: "HOLD",
        entropy: 0.85,
      },
    ],
  },
  "CASE-003": {
    case_id: "CASE-003",
    terminal_state: "HUMAN_REVIEW_REQUIRED",
    final_entropy: 0.0,
    entropy_history: [1.0, 0.65, 0.25, 0.0],
    policy_rule_triggered: "Policy Rule 5: Full Corroboration & Zero Anomalies -> Human Adjudicator Queue",
    similarity_score: 0.98,
    contradictions: [],
    quarantine_log: {
      blocked_fields: ["exact_address", "biometric_hash", "contact_number"],
      safe_fields: ["age", "origin", "timeline", "physical_markers"],
      zero_pii_verified: true,
    },
    uncertainty_budget: {
      identity: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.98,
        sources: ["birth_registry_extract", "aadhaar_match_token"],
      },
      origin: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.98,
        sources: ["varanasi_police_records_FIR_88"],
      },
      timeline: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.98,
        sources: ["cctv_godowlia_chowk_cam14", "rail_manifest_varanasi"],
      },
      physical_markers: {
        required: true,
        status: "CONFIRMED",
        confidence: 0.98,
        sources: ["red_wristband_verified", "medical_record_pmch"],
      },
    },
    steps: [
      {
        step: 1,
        node: "manager",
        plane: "Plane 1: Intake & Security Audit",
        title: "Case Manager Agent",
        icon: "🧭",
        tool: "scan_prompt_injection() & Dynamic Uncertainty Routing",
        toolType: "Security Audit",
        reasoning:
          "Intake verification passed (Zero adversarial markers). Complete primary report logged from Varanasi Smart City grid. Routing to parallel investigation planes.",
        timestamp: "2026-09-11 13:30:16.120 IST",
        entropy: 1.0,
      },
      {
        step: 2,
        node: "evidence_inv",
        plane: "Plane 2: FastMCP & RAG Investigators",
        title: "Evidence & Context Investigators",
        icon: "🔎",
        tool: "FastMCP: search_case_metadata + ChromaDB Vector RAG",
        toolType: "FastMCP",
        reasoning:
          "Queried FastMCP and ChromaDB hybrid vector store across Varanasi Smart City Grid (Godowlia Chowk Cam-14). Ingested red wristband sighting and transit log match with cosine distance 0.02. All 4 dimensions verified with >0.95 confidence.",
        timestamp: "2026-09-11 13:30:16.430 IST",
        entropy: 0.65,
      },
      {
        step: 3,
        node: "critic",
        plane: "Plane 3: Adversarial Safety Critic",
        title: "Safety Critic Agent",
        icon: "⚖️",
        tool: "Dual-Mode LLM Gateway: audit_contradictions()",
        toolType: "Dual-Mode LLM",
        reasoning:
          "Full contradiction audit executed. Verified: Zero physical discrepancies, timeline transit timestamps align within 4-minute tolerance, age corroboration matches birth certificate extract. Contradiction risk: 0.00.",
        timestamp: "2026-09-11 13:30:16.710 IST",
        entropy: 0.25,
      },
      {
        step: 4,
        node: "policy_eval",
        plane: "The +1 Plane: Deterministic Policy Engine",
        title: "Policy Evaluator Engine",
        icon: "🛡️",
        tool: "Deterministic Governance Engine (Rule 5 Enforced)",
        toolType: "Deterministic Policy",
        reasoning:
          "POLICY RULE 5 SATISFIED: All required evidence dimensions corroborated (confidence 0.98), zero hard contradictions, zero prompt injection anomalies. Under strict human-in-the-loop mandate, AI halts autonomous action and routes to Certified Human Child Welfare Adjudicator queue.",
        timestamp: "2026-09-11 13:30:16.920 IST",
        terminal_state: "HUMAN_REVIEW_REQUIRED",
        entropy: 0.0,
      },
    ],
  },
};

export const MOCK_RAG_SOURCES: RAGSourceEvidence[] = [
  {
    id: "RAG-01",
    source_name: "East Central Railway (ECR) Danapur / Patna Junction CCTV Cam-04",
    facility: "Patna Junction Concourse Platform 2",
    location: "Patna, Bihar",
    checkpoint_coverage: "94.2%",
    handoff_latency: "14m",
    confidence: 0.95,
    snippet:
      "CCTV footage timestamp 2026-09-01 08:26 IST shows subject matching height profile (~150cm) and red shoulder bag at concourse checkpoint. Transferred towards platform 2 express boarding.",
    metadata_tags: ["Transit CCTV", "ECR Danapur", "Patna Junction", "High Resolution"],
  },
  {
    id: "RAG-02",
    source_name: "Birsa Munda Interstate Bus Terminal (ISBT) Bay 4 CCTV",
    facility: "Interstate Transit Concourse Bay 4",
    location: "Ranchi, Jharkhand",
    checkpoint_coverage: "96.8%",
    handoff_latency: "22m",
    confidence: 0.94,
    snippet:
      "Automated optical scan generated 98.4% facial match candidate at bus boarding queue. Subject observed with dark hair, distinct mole on right cheek. Sighting logged for anatomical corroboration.",
    metadata_tags: ["ISBT Transit", "Ranchi Bus Stand", "Facial Scan", "Optical Verification"],
  },
  {
    id: "RAG-03",
    source_name: "Varanasi Smart City Traffic Surveillance Grid CCTV Cam-14",
    facility: "Godowlia Chowk Municipal Camera 14",
    location: "Varanasi, Uttar Pradesh",
    checkpoint_coverage: "98.1%",
    handoff_latency: "8m",
    confidence: 0.98,
    snippet:
      "Smart City HD camera stream logged subject wearing identifiable red wristband at Godowlia Chowk crossing at 18:42 IST. Trajectory consistent with family FIR report and nearby school pedestrian trail.",
    metadata_tags: ["Smart City Grid", "Varanasi CCTV", "Wristband Marker", "Temporal Sync"],
  },
  {
    id: "RAG-04",
    source_name: "Patna Medical College Hospital (PMCH) Pediatric Emergency Triage",
    facility: "Pediatric Emergency Ward B",
    location: "Patna, Bihar",
    checkpoint_coverage: "91.5%",
    handoff_latency: "35m",
    confidence: 0.96,
    snippet:
      "Admissions ledger cross-referenced for missing minor demographic profiles. Zero matching pediatric admissions reported within 72 hours of Patna transit alert.",
    metadata_tags: ["Hospital Records", "PMCH Municipal", "Pediatric Triage", "Negative Match"],
  },
  {
    id: "RAG-05",
    source_name: "Childline 1098 Emergency Transit Help Desk (Varanasi / Patna)",
    facility: "Civic Transit Protection Kiosk",
    location: "Railway Concourse East",
    checkpoint_coverage: "99.0%",
    handoff_latency: "5m",
    confidence: 0.97,
    snippet:
      "Field helpline desk registered initial transit notification and coordinated with station master office without disclosing minor personal contact or residential details.",
    metadata_tags: ["Childline 1098", "Civic Desk", "Field Protection", "Zero PII Transfer"],
  },
];

export const QUARANTINE_SPEC = {
  rule: "FastMCP Pre-LLM Data Minimization Schema Gate",
  enforcement: "Strict Typed Descriptor & Exception Layer before LLM Token Ingestion",
  quarantined_fields: [
    {
      field: "exact_address",
      reason: "Direct residential identifier of minor; strictly prohibited from LLM context",
      status: "BLOCKED",
    },
    {
      field: "biometric_hash",
      reason: "Cryptographic biometric vector (facial/fingerprint template) quarantined in secure vault",
      status: "BLOCKED",
    },
    {
      field: "contact_number",
      reason: "Guardian phone number quarantined; only authorized field officers access via OTP",
      status: "BLOCKED",
    },
  ],
  allowed_fields: [
    { field: "age", reason: "Permitted for demographic categorization", status: "ALLOWED" },
    { field: "origin", reason: "Permitted for geographic transit routing", status: "ALLOWED" },
    { field: "timeline", reason: "Permitted for temporal corridor verification", status: "ALLOWED" },
    {
      field: "physical_markers",
      reason: "Permitted for anatomical corroboration (scars, clothing, height)",
      status: "ALLOWED",
    },
  ],
};
